import { useState } from 'react';
import { ArrowRight, FolderOpen, ImageDown, Images, Paintbrush, Plus, Settings2, Sparkles, WandSparkles, Zap } from 'lucide-react';
import { Modal } from '../components/Modal';
import { useAppStore } from '../stores/app-store';

export function HomePage() {
  const { projects, createProject, openProject, removeProject, importProject, setView } = useAppStore();
  const [createOpen, setCreateOpen] = useState(false); const [name, setName] = useState('Projeto sem título'); const [description, setDescription] = useState('');
  const create = async () => { await createProject(name, description); setCreateOpen(false); };
  return <div className="home-page">
    <header className="home-header"><div><span className="eyebrow"><Sparkles size={14} />ESTÚDIO VISUAL INDEPENDENTE</span><h1>Transforme ideias em<br /><em>imagens memoráveis.</em></h1><p>Crie, edite e organize seus projetos em um fluxo visual seguro — com ferramentas locais e IA opcional.</p><div className="hero-actions"><button className="primary" onClick={() => setCreateOpen(true)}><Plus size={18} />Novo projeto</button><button className="secondary" onClick={() => void importProject()}><FolderOpen size={18} />Importar projeto</button></div></div><div className="hero-art"><div className="art-card card-a"><Paintbrush /></div><div className="art-card card-b"><WandSparkles /></div><div className="art-orbit"><Sparkles /></div><div className="art-caption"><span>Fluxo não destrutivo</span><strong>Original sempre protegido</strong></div></div></header>
    <section className="quick-section"><div className="section-header"><div><span>COMECE POR AQUI</span><h2>O que você quer criar hoje?</h2></div></div><div className="quick-grid"><Quick icon={Sparkles} tone="violet" title="Gerar imagem" text="Comece por uma descrição e controle estilo, composição e saída." onClick={() => setCreateOpen(true)} /><Quick icon={Paintbrush} tone="cyan" title="Editar fotografia" text="Importe uma imagem, desenhe máscaras e crie revisões." onClick={() => setCreateOpen(true)} /><Quick icon={Zap} tone="amber" title="Otimizar imagem" text="Redimensione, converta e comprima localmente." onClick={() => setCreateOpen(true)} /><Quick icon={Images} tone="pink" title="Processamento em lote" text="Abra um projeto e importe múltiplos arquivos de uma vez." onClick={() => setCreateOpen(true)} /></div></section>
    <section className="projects-section"><div className="section-header"><div><span>PROJETOS RECENTES</span><h2>Continue de onde parou</h2></div>{projects.length > 0 && <small>{projects.length} projeto(s) local(is)</small>}</div>{projects.length === 0 ? <div className="projects-empty"><ImageDown size={30} /><div><strong>Nenhum projeto ainda</strong><p>Crie seu primeiro projeto; os arquivos ficarão apenas neste computador.</p></div><button onClick={() => setCreateOpen(true)}>Criar agora <ArrowRight size={15} /></button></div> : <div className="project-grid">{projects.slice(0, 8).map((project) => <article key={project.id} className="project-card"><button className="project-open" onClick={() => void openProject(project)}><div className="project-preview"><span>{project.name.slice(0, 2).toUpperCase()}</span></div><div><strong>{project.name}</strong><small>{new Date(project.updatedAt).toLocaleDateString('pt-BR')}</small><p>{project.description || 'Projeto visual'}</p></div></button><button className="project-remove" onClick={() => { if (window.confirm(`Remover “${project.name}” e seus arquivos locais?`)) void removeProject(project); }}>Remover</button></article>)}</div>}</section>
    <footer className="home-footer"><button onClick={() => setView('library')}><Images size={16} />Galeria e biblioteca</button><button onClick={() => setView('settings')}><Settings2 size={16} />Configurar provedores</button></footer>
    {createOpen && <Modal title="Novo projeto" onClose={() => setCreateOpen(false)}><label className="field"><span>Nome</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>Descrição opcional</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className="modal-actions"><button className="secondary" onClick={() => setCreateOpen(false)}>Cancelar</button><button className="primary" disabled={!name.trim()} onClick={() => void create()}>Criar projeto</button></div></Modal>}
  </div>;
}

function Quick({ icon: Icon, tone, title, text, onClick }: { icon: typeof Sparkles; tone: string; title: string; text: string; onClick: () => void }) { return <button className="quick-card" onClick={onClick}><span className={`quick-icon ${tone}`}><Icon size={22} /></span><strong>{title}</strong><p>{text}</p><span className="quick-link">Abrir fluxo <ArrowRight size={14} /></span></button>; }
