import { Activity, Ban, CheckCircle2, Clock3, RefreshCcw, TriangleAlert } from 'lucide-react';
import { useEffect } from 'react';
import { useAppStore } from '../stores/app-store';

const statusLabel: Record<string, string> = { queued: 'Aguardando', validating: 'Validando', preparing: 'Preparando arquivos', sending: 'Enviando', processing: 'Processando', receiving: 'Recebendo', saving: 'Salvando', completed: 'Concluído', cancelled: 'Cancelado', failed: 'Falhou' };

export function JobsPage() {
  const { jobs, reloadJobs, notify } = useAppStore();
  useEffect(() => { void reloadJobs(); const unsubscribe = window.illustrator.jobs.subscribe(() => void reloadJobs()); return unsubscribe; }, [reloadJobs]);
  return <div className="content-page"><PageTitle eyebrow="FILA PERSISTENTE" title="Trabalhos" text="Acompanhe operações locais e de IA. Repetições cobradas exigem sua ação explícita." /><div className="job-summary"><Summary icon={Activity} label="Total" value={jobs.length} /><Summary icon={Clock3} label="Em andamento" value={jobs.filter((job) => !['completed', 'failed', 'cancelled'].includes(job.status)).length} /><Summary icon={CheckCircle2} label="Concluídos" value={jobs.filter((job) => job.status === 'completed').length} /><Summary icon={TriangleAlert} label="Falhas" value={jobs.filter((job) => job.status === 'failed').length} /></div><div className="table-card">{jobs.length === 0 ? <div className="page-empty"><Activity size={30} /><strong>Nenhum trabalho na fila</strong><p>As gerações e edições aparecerão aqui.</p></div> : jobs.map((job) => <div className="job-row" key={job.id}><span className={`job-state ${job.status}`} /> <div><strong>{job.operation === 'generate' ? 'Geração de imagem' : job.operation === 'edit' ? 'Edição de imagem' : 'Processamento local'}</strong><small>{job.providerId} · {job.modelId}</small></div><div className="progress"><i style={{ width: `${job.progress}%` }} /><span>{job.progress}%</span></div><span className="status-label">{statusLabel[job.status] ?? job.status}</span><div className="row-actions">{!['completed', 'failed', 'cancelled'].includes(job.status) && <button title="Cancelar" onClick={() => void window.illustrator.jobs.cancel(job.id).then(() => reloadJobs())}><Ban size={15} /></button>}{['failed', 'cancelled'].includes(job.status) && <button title="Repetir manualmente" onClick={() => { if (window.confirm('Repetir este trabalho? Operações de nuvem podem gerar nova cobrança.')) void window.illustrator.jobs.retry(job.id).then((result) => { void reloadJobs(); notify({ kind: result.ok ? 'success' : 'error', message: result.ok ? 'Trabalho repetido.' : result.error?.message ?? 'Falha.' }); }); }}><RefreshCcw size={15} /></button>}</div>{job.errorMessage && <p className="job-error">{job.errorMessage}</p>}</div>)}</div></div>;
}

function Summary({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: number }) { return <div><Icon size={18} /><span>{label}</span><strong>{value}</strong></div>; }
export function PageTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <header className="page-title"><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></header>; }
