import { Archive, BookImage, CopyPlus, Palette, Plus, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Modal } from '../components/Modal';
import { unwrap, useAppStore } from '../stores/app-store';
import { PageTitle } from './JobsPage';

export function LibraryPage() {
  const { profiles, styles, reloadLibrary, notify } = useAppStore(); const [mode, setMode] = useState<'profile' | 'style' | null>(null);
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [strict, setStrict] = useState(false); const [category, setCategory] = useState('Personalizado');
  const save = async () => {
    try {
      if (mode === 'profile') unwrap(await window.illustrator.profiles.save({ name, description, isStrict: strict, content: { mainInstruction: description } }));
      else unwrap(await window.illustrator.styles.save({ name, category, description }));
      await reloadLibrary(); setMode(null); setName(''); setDescription(''); notify({ kind: 'success', message: mode === 'profile' ? 'Perfil versionável criado.' : 'Estilo salvo.' });
    } catch (error) { notify({ kind: 'error', message: error instanceof Error ? error.message : 'Falha ao salvar.' }); }
  };
  return <div className="content-page"><PageTitle eyebrow="BIBLIOTECA REUTILIZÁVEL" title="Perfis e estilos" text="Crie direções consistentes sem limitar sua liberdade visual." /><section className="library-section"><div className="section-header"><div><span>PERFIS DE ILUSTRADOR</span><h2>Agentes visuais reutilizáveis</h2></div><button className="primary-small" onClick={() => setMode('profile')}><Plus size={16} />Novo perfil</button></div><div className="library-grid">{profiles.filter((profile) => !profile.isArchived).map((profile) => <article className="library-card" key={profile.id}><span className="library-icon"><ShieldCheck size={19} /></span><div><strong>{profile.name}</strong><small>Versão {profile.version} · {profile.isStrict ? 'modo estrito' : 'modo flexível'}</small><p>{profile.description || 'Sem descrição.'}</p></div><button title="Duplicar" onClick={() => { void window.illustrator.profiles.save({ name: `${profile.name} — cópia`, description: profile.description, isStrict: profile.isStrict, content: profile.content }).then(() => reloadLibrary()); }}><CopyPlus size={15} /></button><button title="Arquivar" onClick={() => { void window.illustrator.profiles.archive(profile.id).then(() => reloadLibrary()); }}><Archive size={15} /></button></article>)}{profiles.filter((profile) => !profile.isArchived).length === 0 && <div className="mini-library-empty"><BookImage /><p>Crie um perfil para reutilizar regras, estilo e preferências.</p></div>}</div></section><section className="library-section"><div className="section-header"><div><span>ESTILOS EDITÁVEIS</span><h2>Biblioteca visual</h2></div><button className="secondary" onClick={() => setMode('style')}><Plus size={16} />Novo estilo</button></div><div className="style-grid">{styles.map((style) => <article key={style.id}><span><Palette size={16} /></span><strong>{style.name}</strong><small>{style.category}</small><p>{style.description}</p></article>)}</div></section>{mode && <Modal title={mode === 'profile' ? 'Novo Perfil de Ilustrador' : 'Novo estilo'} onClose={() => setMode(null)}><label className="field"><span>Nome</span><input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>Descrição e instruções</span><textarea rows={5} value={description} onChange={(event) => setDescription(event.target.value)} /></label>{mode === 'profile' ? <label className="inline-check"><input type="checkbox" checked={strict} onChange={(event) => setStrict(event.target.checked)} />Modo estrito para regras bloqueadas</label> : <label className="field"><span>Categoria</span><input value={category} onChange={(event) => setCategory(event.target.value)} /></label>}<div className="modal-actions"><button className="secondary" onClick={() => setMode(null)}>Cancelar</button><button className="primary" disabled={!name.trim() || !description.trim()} onClick={() => void save()}>Salvar</button></div></Modal>}</div>;
}
